language: node_js
node_js:
  - 'stable'
sudo: false
env:
  - secure: "CT5ORogIuwvxzHojQnOSNbADT6yql3aVP+s6kH9VqdVZzAEzawFEhFeV6i9eIzjsKYAqjEepJ9WxYwBVhNWnEqOVt9ECoqSgmiZdG229ueuPppwWUb5MCIXxlZepfDbf+g/JPWqY3P1muR3xJZwRxah4Vxsy+ehenPicnXC0NWULIVWTr/pn0X07oQcLtEwXmvQp5k1HfsMtxZ0BnRNBsMEZ+Smq8SFipAPIMLav2jJxxIjMp8ARNCWMUSLBH+0ydZFmBTRuUxkydBv46b+DrowROTWChz5Yfe6zyQ1HxwzmoBDUnHjkE/HcwIJ/4Ab0xKPiHVuXP9wh8bmPCgkPsm1OlWocjU43BHpuxo8JswroMJ0ctXZYgVOjS1b3GMBgpHrlhrXKCQcR7fMTNiTzGJ2hf+9LNBAYoQmGaRsn9sZnTmyuTetauTtP1EZt4ID6Nw5V1wztoGwGSL2xDf+iOPRTSCD+t7nMSoZbh87ZStYF4vLrzJhF6/dH8Z6XImHc7QkEWNqKJmYyZcLuYzzxJiphA8+0tiEF9uvOpZUyz29+FHY79XEphq7KrzMqku0xSLCVlUplyjsf0WQlOWJh9eMXEd7GbvkvpvB8YDaZx1XPMvt5NpHRw6BmJ8ktYg+K2in1h46MqL7PwwDLzSBN464axQi+G+L89YT8CtCQfJg="
install:
  - npm install -g babel-eslint faucet eslint eslint-config-js
  - npm install
